project:
  name: ventas360_pipeline
  airflow_version: 2.7.0
  runtime_version: 12.4.0
  description: "Pipeline ETL para Ventas360 con dbt y Snowflake"

  env:
    - AIRFLOW_HOME=/usr/local/airflow
    - DBT_ENV=/usr/local/airflow/dbt_venv
